//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.08 at 07:45:05 PM BST 
//


package ConversionClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="country" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="golds" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="silvers" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="bronzes" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="medalcolection">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="medal" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="categorie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="medal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="winner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "country"
})
@XmlRootElement(name = "countrycolection")
public class Countrycolection {

    protected List<Countrycolection.Country> country;

    /**
     * Gets the value of the country property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the country property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Countrycolection.Country }
     * 
     * 
     */
    public List<Countrycolection.Country> getCountry() {
        if (country == null) {
            country = new ArrayList<Countrycolection.Country>();
        }
        return this.country;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="shortname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="golds" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="silvers" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="bronzes" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="medalcolection">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="medal" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="categorie" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="medal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="winner" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nation",
        "shortname",
        "golds",
        "silvers",
        "bronzes",
        "total",
        "medalcolection"
    })
    public static class Country {

        @XmlElement(required = true)
        protected String nation;
        @XmlElement(required = true)
        protected String shortname;
        protected int golds;
        protected int silvers;
        protected int bronzes;
        protected int total;
        @XmlElement(required = true)
        protected Countrycolection.Country.Medalcolection medalcolection;

        /**
         * Gets the value of the nation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNation() {
            return nation;
        }

        /**
         * Sets the value of the nation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNation(String value) {
            this.nation = value;
        }

        /**
         * Gets the value of the shortname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortname() {
            return shortname;
        }

        /**
         * Sets the value of the shortname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShortname(String value) {
            this.shortname = value;
        }

        /**
         * Gets the value of the golds property.
         * 
         */
        public int getGolds() {
            return golds;
        }

        /**
         * Sets the value of the golds property.
         * 
         */
        public void setGolds(int value) {
            this.golds = value;
        }

        /**
         * Gets the value of the silvers property.
         * 
         */
        public int getSilvers() {
            return silvers;
        }

        /**
         * Sets the value of the silvers property.
         * 
         */
        public void setSilvers(int value) {
            this.silvers = value;
        }

        /**
         * Gets the value of the bronzes property.
         * 
         */
        public int getBronzes() {
            return bronzes;
        }

        /**
         * Sets the value of the bronzes property.
         * 
         */
        public void setBronzes(int value) {
            this.bronzes = value;
        }
        /**
         * Gets the value of the total property.
         * 
         */
        public int getTotal() {
            return total;
        }

        /**
         * Sets the value of the total property.
         * 
         */
        public void setTotal(int value) {
            this.total = value;
        }
        /**
         * Gets the value of the medalcolection property.
         * 
         * @return
         *     possible object is
         *     {@link Countrycolection.Country.Medalcolection }
         *     
         */
        public Countrycolection.Country.Medalcolection getMedalcolection() {
        	 if (medalcolection == null) {
        		 medalcolection = new Countrycolection.Country.Medalcolection();
             }
             return this.medalcolection;
        }

        /**
         * Sets the value of the medalcolection property.
         * 
         * @param value
         *     allowed object is
         *     {@link Countrycolection.Country.Medalcolection }
         *     
         */
        public void setMedalcolection(Countrycolection.Country.Medalcolection value) {
            this.medalcolection = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="medal" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="categorie" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="medal" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="winner" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "medal"
        })
        public static class Medalcolection {

            protected List<Countrycolection.Country.Medalcolection.Medal> medal;

            /**
             * Gets the value of the medal property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the medal property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMedal().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Countrycolection.Country.Medalcolection.Medal }
             * 
             * 
             */
            public List<Countrycolection.Country.Medalcolection.Medal> getMedal() {
                if (medal == null) {
                    medal = new ArrayList<Countrycolection.Country.Medalcolection.Medal>();
                }
                return this.medal;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="categorie" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="medal" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="winner" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "categorie",
                "sport",
                "medal",
                "winner"
            })
            public static class Medal {

                @XmlElement(required = true)
                protected String categorie;
                @XmlElement(required = true)
                protected String sport;
                @XmlElement(required = true)
                protected String medal;
                @XmlElement(required = true)
                protected String winner;

                /**
                 * Gets the value of the categorie property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCategorie() {
                    return categorie;
                }

                /**
                 * Sets the value of the categorie property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCategorie(String value) {
                    this.categorie = value;
                }

                /**
                 * Gets the value of the sport property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSport() {
                    return sport;
                }

                /**
                 * Sets the value of the sport property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSport(String value) {
                    this.sport = value;
                }

                /**
                 * Gets the value of the medal property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMedal() {
                    return medal;
                }

                /**
                 * Sets the value of the medal property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMedal(String value) {
                    this.medal = value;
                }

                /**
                 * Gets the value of the winner property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWinner() {
                    return winner;
                }

                /**
                 * Sets the value of the winner property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWinner(String value) {
                    this.winner = value;
                }

            }

        }

    }

}
