//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.08 at 07:45:05 PM BST 
//


package ConversionClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ConversionClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ConversionClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Countrycolection }
     * 
     */
    public Countrycolection createCountrycolection() {
        return new Countrycolection();
    }

    /**
     * Create an instance of {@link Countrycolection.Country }
     * 
     */
    public Countrycolection.Country createCountrycolectionCountry() {
        return new Countrycolection.Country();
    }

    /**
     * Create an instance of {@link Countrycolection.Country.Medalcolection }
     * 
     */
    public Countrycolection.Country.Medalcolection createCountrycolectionCountryMedalcolection() {
        return new Countrycolection.Country.Medalcolection();
    }

    /**
     * Create an instance of {@link Countrycolection.Country.Medalcolection.Medal }
     * 
     */
    public Countrycolection.Country.Medalcolection.Medal createCountrycolectionCountryMedalcolectionMedal() {
        return new Countrycolection.Country.Medalcolection.Medal();
    }

}
